<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Page;
use AppBundle\Entity\Pagesection;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagesectionRepository extends \Doctrine\ORM\EntityRepository
{

    public function getContents(Page $page)
    {
        $query = $this->createQueryBuilder('p')
            ->where('p.page = :page')
            ->setParameter('page',$page)
            ->getQuery();
        $results = $query->getResult();
        return $results;
    }
}
