<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Page;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Doctrine\ORM\EntityRepository
{

    public function getHeader($section)
    {
        $query = $this->createQueryBuilder('p')
            ->where('p.section = :section')
            ->setParameter('section',$section)
            ->setMaxResults(1)
            ->getQuery();
        $results = $query->getOneOrNullResult();
        return $results;
    }

    public function getContents($section)
    {
        $query = $this->createQueryBuilder('p')
            ->where('p.section = :section')
            ->setParameter('section',$section)
            ->getQuery();
        $results = $query->getResult();
        return $results;
    }
}
