<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Post;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{

    public function getLastPost()
    {
        $query = $this->createQueryBuilder('p')
            ->where('p.publishedAt IS NOT NULL')
            ->andWhere('p.status = :status')
            ->setParameter('status',Post::PUBLISHED)
            ->orderBy('p.publishedAt', 'DESC')
            ->setMaxResults(1)
            ->getQuery();
        $results = $query->getOneOrNullResult();
        return $results;
    }

}
