<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Post;

/**
 * PostRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPost($offset = 1)
    {
        $query = $this->createQueryBuilder('p')
            ->where('p.publishedAt IS NOT NULL')
            ->andWhere('p.status = :status')
            ->setParameter('status', Post::PUBLISHED)
            ->andWhere('p.status = :status')
            ->setParameter('status', Post::PUBLISHED)
            ->orderBy('p.publishedAt', 'DESC')
            ->setMaxResults(1)
            ->setFirstResult($offset)
            ->getQuery();
        $results = $query->getOneOrNullResult();

        return $results;
    }

    public function getPostCount()
    {
        $count = $this->createQueryBuilder('p')
            ->select('count(p.id)')
            ->where('p.publishedAt IS NOT NULL')
            ->andWhere('p.status = :status')
            ->setParameter('status', Post::PUBLISHED)
            ->orderBy('p.publishedAt', 'DESC')
            ->getQuery()
            ->getSingleScalarResult();

        return $count - 1;
    }
}
