
homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
    methods: [get]

courses:
    path:     /cours
    defaults: { _controller: AppBundle:Default:courses }
    methods: [get]

user_register:
    path:     /register
    defaults: { _controller: AppBundle:Default:register }
    methods: [get,post]

admin_homepage:
    path:     /admin
    defaults: { _controller: AppBundle:Admin\Default:index }
    methods: [get]


security_login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }
    methods: [get,post]

security_login_check:
    path:     /login
    defaults: { _controller: AppBundle:Security:loginCheck }
    methods: [get]


logout:
    path: /logout

admin_import:
    resource: "@AppBundle/Resources/config/routing/admin.yml"
    prefix: /admin


