homepage:
    path:     /
    defaults: { _controller: AppBundle:Etmd:index }
    methods: [get]

training:
    path:     /training
    defaults: { _controller: AppBundle:Training:index }
    methods: [get]

classroom:
    path:     /classroom
    defaults: { _controller: AppBundle:Classroom:index }
    methods: [get]

privateLessons:
    path:     /privateLessons
    defaults: { _controller: AppBundle:PrivateLessons:index }
    methods: [get]

