

homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
    methods: [get]

user_register:
    path:     /register
    defaults: { _controller: AppBundle:Default:register }
    methods: [get,post]

admin_homepage:
    path:     /admin
    defaults: { _controller: AppBundle:Admin\Default:index }
    methods: [get]


security_login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }
    methods: [get,post]

security_login_check:
    path:     /login
    defaults: { _controller: AppBundle:Security:loginCheck }
    methods: [get]


logout:
    path: /logout


admin_user_index:
    path:     /admin/user
    defaults: { _controller: AppBundle:Admin\User:index }
    methods:  GET

admin_user_show:
    path:     /admin/users/{id}/show
    defaults: { _controller: AppBundle:Admin\User:show }
    methods:  GET

admin_user_new:
    path:     /admin/users/new
    defaults: { _controller: AppBundle:Admin\User:new }
    methods:  [GET, POST]

admin_user_edit:
    path:     /admin/users/{id}/edit
    defaults: { _controller: AppBundle:Admin\User:edit }
    methods:  [GET, POST,DELETE]

admin_user_delete:
    path:     /admin/users/{id}/delete
    defaults: { _controller: AppBundle:Admin\User:delete }
    methods:  DELETE
