
homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
    methods: [get]

course:
    path:     /cours
    defaults: { _controller: AppBundle:Default:course }
    methods: [get]

workshop:
    path:     /ateliers
    defaults: { _controller: AppBundle:Default:workshop }
    methods: [get]

residence:
    path:     /residence
    defaults: { _controller: AppBundle:Default:residence }
    methods: [get]

training:
    path:     /formation
    defaults: { _controller: AppBundle:Default:training }
    methods: [get]

contactus:
    path:     /nous-contacter
    defaults: { _controller: AppBundle:Default:contactus }
    methods: [get]

user_register:
    path:     /register
    defaults: { _controller: AppBundle:Default:register }
    methods: [get,post]

admin_homepage:
    path:     /admin
    defaults: { _controller: AppBundle:Admin\Default:index }
    methods: [get]


security_login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }
    methods: [get,post]

security_login_check:
    path:     /login
    defaults: { _controller: AppBundle:Security:loginCheck }
    methods: [get]


logout:
    path: /logout

admin_import:
    resource: "@AppBundle/Resources/config/routing/admin.yml"
    prefix: /admin


