homepage:
    path:     /
    defaults: { _controller: AppBundle:Etmd:index }
    methods: [get]

ateliers:
    path:     /ateliers
    defaults: { _controller: AppBundle:Etmd:ateliers }
    methods: [get]

cours_collectifs:
    path:     /cours_collectifs
    defaults: { _controller: AppBundle:Etmd:cours_collectifs }
    methods: [get]

cours_particuliers:
    path:     /cours_particuliers
    defaults: { _controller: AppBundle:Etmd:cours_particuliers }
    methods: [get]

