

homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
    methods: [get]

user_register:
    path:     /register
    defaults: { _controller: AppBundle:Default:register }
    methods: [get,post]

ldm_admin:
    resource: "@LdmAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

security_login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }
    methods: [get,post]

security_login_check:
    path:     /login
    defaults: { _controller: AppBundle:Security:loginCheck }
    methods: [get]


logout:
    path: /logout
