# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    form_authenticator:
        class: AppBundle\Security\FormAuthenticator
        arguments: ['@router', '@form.factory', '@security.user_password_encoder.generic']

    service_post:
        class: AppBundle\Service\PostService
        arguments: [ "@doctrine.orm.entity_manager" ]

    service_user:
        class: AppBundle\Service\UserService
        arguments: [ "@doctrine.orm.entity_manager" ]

    AppBundle\EventListener\PostListener:
            tags:
                - { name: doctrine.event_listener, event: preUpdate }
                - { name: doctrine.event_listener, event: prePersist }

    AppBundle.twig.html_extension:
        class: AppBundle\Twig\Extension\HtmlExtension
        tags:
            - { name: twig.extension }