# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    form_authenticator:
        class: AppBundle\Security\FormAuthenticator
        arguments: ['@router', '@form.factory', '@security.user_password_encoder.generic']

    service_post:
        class: AppBundle\Service\PostService
        arguments: [ "@doctrine.orm.entity_manager", "@security.token_storage" ]

    service_user:
        class: AppBundle\Service\UserService
        arguments: [ ]

    service_page:
        class: AppBundle\Service\PageService
        arguments: [ "@doctrine.orm.entity_manager" ]

    service_role:
        class: AppBundle\Service\RoleService
        arguments: [ "@security.role_hierarchy" ]

    service_newsletter:
        class: AppBundle\Service\NewsletterService
        arguments: [ "@doctrine.orm.entity_manager", "%mailchimp%" ]

    service_mailer:
        class: AppBundle\Service\MailerService
        arguments: ['@Swift_Mailer']

    AppBundle\EventListener\PostListener:
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: prePersist }

    AppBundle\EventListener\PageListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    AppBundle.twig.html_extension:
        class: AppBundle\Twig\Extension\HtmlExtension
        tags:
            - { name: twig.extension }

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

