admin_user_import:
    resource: "admin/user.yml"
    prefix: /user

admin_post_import:
    resource: "admin/post.yml"
    prefix: /post

admin_page_import:
    resource: "admin/page.yml"
    prefix: /page